In [ ]:
import  pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
from google.colab import files
upload=files.upload()

Saving IMDb Movies India.csv to IMDb Movies India.csv

In [ ]:
movie=pd.read_csv('IMDb Movies India.csv',encoding='ISO-8859-1')
movie.head()

                                 Name  ...          Actor 3
0                                      ...  Rajendra Bhatia
1  #Gadhvi (He thought he was Gandhi)  ...    Arvind Jangid
2                         #Homecoming  ...       Roy Angana
3                             #Yaaram  ...  Siddhant Kapoor
4                   ...And Once Again  ...      Antara Mali

[5 rows x 10 columns]

In [ ]:
movie.shape

(15509, 10)

In [ ]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
movie['Rating'].fillna (value= movie['Rating'].mean(),inplace = True)
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    15509 non-null  float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
x = movie["Votes"].mode()[0]

movie["Votes"].fillna(x, inplace = True)
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    15509 non-null  float64
 5   Votes     15509 non-null  object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
movie['Genre'].fillna (value= movie['Genre'].mode()[0],inplace = True)
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     15509 non-null  object
 4   Rating    15509 non-null  float64
 5   Votes     15509 non-null  object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()

In [ ]:
x = movie.loc[:,movie.columns != 'Actor 3' ]
x.head()

                                 Name  ... Genre_War
0                                      ...         0
1  #Gadhvi (He thought he was Gandhi)  ...         0
2                         #Homecoming  ...         0
3                             #Yaaram  ...         0
4                   ...And Once Again  ...         0

[5 rows x 672 columns]

In [ ]:
x = movie.loc[:,movie.columns != 'Actor 1' ]
x.head()

                                 Name  ... Genre_War
0                                      ...         0
1  #Gadhvi (He thought he was Gandhi)  ...         0
2                         #Homecoming  ...         0
3                             #Yaaram  ...         0
4                   ...And Once Again  ...         0

[5 rows x 672 columns]

In [ ]:
x = movie.loc[:,movie.columns != 'Genre ' ]
x.head()

                                 Name  ... Genre_War
0                                      ...         0
1  #Gadhvi (He thought he was Gandhi)  ...         0
2                         #Homecoming  ...         0
3                             #Yaaram  ...         0
4                   ...And Once Again  ...         0

[5 rows x 673 columns]